// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerRecord } from "./PeerRecord";
import type { ScanId } from "./ScanId";

/**
 * Every event the backend can push to the frontend. Externally tagged so
 * `serde_json` round-trips it as `{"PeerDiscovered": {...}}` etc.
 */
export type AppEvent = { "ScanStarted": { scan_id: ScanId, } } | { "PeerDiscovered": { scan_id: ScanId, peer: PeerRecord, } } | { "ScanFinished": { scan_id: ScanId, total_peers: number, } };
