// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One peer discovered during a network scan.
 */
export type PeerRecord = { id: string, address: string, latency_ms: number, };
