// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for the `start_scan` Tauri command. Same crate, same
 * derive macro — the frontend `invoke()` call site picks up the
 * generated `StartScanRequest` type and TypeScript refuses to compile
 * if the caller forgets a required field.
 */
export type StartScanRequest = { cidr: string, timeout_ms: number, };
