// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanId } from "./ScanId";

/**
 * Response payload for the `start_scan` command. Tauri's `invoke`
 * returns a JSON value; routing it through `StartScanResponse` lets the
 * TS callsite destructure with full typing.
 */
export type StartScanResponse = { scan_id: ScanId, estimated_peers: number, };
